site_name : PayEx Checkout
theme : readthedocs
repo_url : https://github.com/PayEx/PayEx.Checkout.Documentation
site_favicon : favicon.png
# TODO site_url: https://checkout.payex.com
# TODO site_description: modern payment solution
site_author : PayEx Team User Experience #TODO change
copyright : Copyright Â© PayEx. All Rights Reserved.

pages :
- Home : index.md
- Requirements : requirements.md
- Getting started : gettingStarted.md
- Frontend :
  - Configuration reference : configurationReference.md
- API :
  - Overview : api.md
  - Payment : payment.md
  - Address : address.md
  - Transaction : transaction.md
- Callbacks : callbacks.md
